### ISSUE TITLE
Missing dependency errors should show file name

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#57] opened 2022-03-01 10:52 UTC
When a dependency is missing, the error message does not show which file contains the dangling import statement:
```
$ lake build
info: mathlib: trying to update ./lean_packages/mathlib to revision f472efc94837eb04f957b952b3c8d82428d118f1
error: no such file or directory (error code: 2)
  file: ././Mathport/Util/While.lean
error: build failed
```
I would expect the error message to contain the file `Mathport/Syntax/Translate/Basic.lean`.

**Comment by tydeu** [comment] 2022-03-01 15:56
Duplicate of #25?

**Closed** 2022-03-01 15:56 UTC
Labels: duplicate, enhancement

**Comment by gebner** [comment] 2022-03-01 16:05
Oops, sorry.  You're right, this is a duplicate.
