### ISSUE TITLE
Feature request: update a single dependency

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lake#148] opened 2023-01-15 22:11 UTC
Currently `lake update` will bump the revision of *all* packages stored in the `lake-manifest.json`, but sometimes we just want to bump one of them. For example, when `DepA` introduced new features but `DepB` made breaking changes, the only way to update `DepA` but not `DepB` currently is to manually edit `lake-manifest.json`.

A concrete syntax might look like `lake update` to update everything and `lake update [pkg1, [pkg2, ..]]` to update only `pkg1, pkg2, ..`.

**Comment by tydeu** [comment] 2023-08-03 01:08
@Vtec234 About this feature request. In your model, would `lake update pkg1` update just `pkg1` or also its transitive dependencies?

**Comment by Vtec234** [comment] 2023-08-03 05:19
@tydeu looking at this now, I think it might be a bit of an XY problem. The original motivation was what we currently have in mathlib4:
```lean
require std from git "https://github.com/leanprover/std4" @ "main"
require Qq from git "https://github.com/gebner/quote4" @ "master"
require aesop from git "https://github.com/JLimperg/aesop" @ "master"
require Cli from git "https://github.com/mhuisi/lean4-cli.git" @ "nightly"
require proofwidgets from git "https://github.com/EdAyers/ProofWidgets4" @ "v0.0.13"
```

Now suppose I set `proofwidgets` to `v0.0.14`. I wish to run `lake update` to bump it in the `lake-manifest.json`. But! This may also bump `std` to a broken version because we import the `main` branch. So I wish to run `lake update proofwidgets` instead.

Ultimately, that feels like a workaround fo missing semantic versioning, or Stackage sets, or some such as was also discussed at length [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.22Perfect.20world.22.20dependency.20management). For this reason, I would say feel free to close this (or at least not implement until a legitimate use case comes up).

**Comment by Kha** [comment] 2023-08-03 08:10
For what it's worth, Nix Flakes is one example of a dependency system not based on semantic versioning that still provides a clean distinction between recreating the lockfile, upgrading a single dependency, and upgrading all dependencies. So I think this feature request is valid. I did find it problematic when I had to specify to run `lake update` in the documentation on using mathlib4 as a dependency when what I really wanted was the first and the second action just mentioned, respectively.

**Comment by tydeu** [comment] 2023-08-03 13:59
@Kha 

>  what I really wanted was the first and the second action just mentioned, respectively.

What is the use case for recreating the lockfile without updating any dependencies?

**Comment by tydeu** [comment] 2023-08-03 14:22
@Kha Ah, I would call that "updating" the new dependency to that latest revision specified in the lakefile, but I can see how that might not be consider an update. Regardless, the important thing is that this case could still be handled by the original `lake updat pkg1 ...` feature request (where `pkg1` equals the new dependency), right? That is, we do not need another command just for regenerating the manifest without any additions/deletions?

**Comment by Kha** [comment] 2023-08-03 14:29
What's the correct command to call after deleting a dependency then?

**Comment by tydeu** [comment] 2023-08-03 14:44
@Kha Likely `lake update deletedPkg`. My thought process on this feature would be that it would filter changes only to the packages specified.

**Comment by Kha** [comment] 2023-08-03 15:08
I have to say that would be a surprising workflow to me. Does any other package manager work like this?

**Comment by tydeu** [comment] 2023-08-03 15:38
@Kha 

> I have to say that would be a surprising workflow to me. Does any other package manager work like this?

Yes, `lake update` works essentially exactly like [`bundle update`](https://bundler.io/v2.4/man/bundle-update.1.html) does for Ruby's package manager (RubyGems / Bundler) where `lakefile.lean` = `Gemfile` and `lake-manifest.json` = `Gemfile.lock`.

**Comment by tydeu** [comment] 2023-08-03 16:51
@Kha No, with bundler, `bundle install` will just install the dependencies from the `Gemfile.lock`, it will only fall back to the `Gemfile` if `Gemfile.lock` does not exist. From the `bundle update` docs:

> When you run [bundle install(1)](https://bundler.io/v2.4/man/bundle-install.1.html) the first time, bundler will resolve all of the dependencies, all the way down, and install what you need: [...]
>
> As you can see, even though you have two gems in the [Gemfile(5)](https://bundler.io/v2.4/man/gemfile.5.html), your application needs 26 different gems in order to run. Bundler remembers the exact versions it installed in `Gemfile.lock`. The next time you run [bundle install(1)](https://bundler.io/v2.4/man/bundle-install.1.html), bundler skips the dependency resolution and installs the same gems as it installed last time.

>
> After checking in the `Gemfile.lock` into version control and cloning it on another machine, running [bundle install(1)](https://bundler.io/v2.4/man/bundle-install.1.html) will still install the gems that you installed last time. You don't need to worry that a new release of `erubis` or `mail` changes the gems you use.

>
> However, from time to time, you might want to update the gems you are using to the newest versions that still match the gems in your [Gemfile(5)](https://bundler.io/v2.4/man/gemfile.5.html).

>
> To do this, run `bundle update --all`, which will ignore the Gemfile.lock, and resolve all the dependencies again. Keep in mind that this process can result in a significantly different set of the 25 gems, based on the requirements of new gems that the gem authors released since the last time you ran `bundle update --all`.

**Comment by Kha** [comment] 2023-08-03 20:09
> `bundle install` will just install the dependencies from the `Gemfile.lock`

How does that rhyme with the first sentence from my link?

> When you make a change to the [Gemfile(5)](https://bundler.io/v2.4/man/gemfile.5.html) and then run bundle install, Bundler will update only the gems that you modified.

So does or does it not resync the lockfile with the Gemfile?

**Comment by tydeu** [comment] 2023-08-04 17:41
@Kha I wrote reply to your inquire yesterday, but appears I forgot to actually press the button to post it, so it is now lost. 🤦‍♂️ Hopefully, I can recall something close to what I meant to have said. Here is an attempt to do so:

I have not use bundler in a long while, so my first-hand experience is quite rusty, so I am mostly going of the documentation. My understanding is that if you modify a gem's specification in the Gemfile directly that will trigger a "conservative update" for a "bundle install". I believe this implemented by storing something like the `inputRev?` of Lake or Nix in `Gemfile.lock` to determine if the Gemfile has changed. The "conersvative update" will update the modified gems and any non-overlapping dependencies (and save the changes to the `Gemfile.lock`). It will not update other gems to their latest legal version or attempt to resolve conflicts between gems. Any such updates will require a manual invocation of `bundle update` to update the `Gemfile.lock`.

Connecting this back to this issue, Wojciech's original example of updating a package to it latest version within the same specifier (i.e., the latest `mater`, `nightly`, or `v1.0.x`) would require a `bundle update` in Ruby and not be part of the "conservative update". Instead, only a change of specifier (e.g., `master` to `nightly` or `v1.0.x` to `v2.0.x`) would trigger such an update. Lake does not use such a "conservative update" partly because specifiers do not change often and partly because the current parallel of `bundle install` (e.g., downloading dependencies) is part of the build process, and, for the reasons discussed in [lake#138](https://github.com/leanprover/lake/pull/138), we decided that updating dependencies and building the package should be disjoint operations.

**Comment by Kha** [comment] 2023-08-07 12:24
Thanks for the explanation. So in summary, having separate commands for syncing the lockfile (and dep checkouts) and for upgrading dependencies seems to be a common design, and `lake update deletedPkg` likely is *not* the way to go :) .

**Comment by Kha** [comment] 2023-08-07 12:33
If we want more data before we make a decision here, perhaps a survey of (prominent) package managers regarding these properties would be helpful. Ideally including their reasoning but that's probably much harder to find out.

> for the reasons discussed in [lake#138](https://github.com/leanprover/lake/pull/138), we decided that updating dependencies and building the package should be disjoint operations

From a quick scan I did not find this discussion btw

**Comment by tydeu** [comment] 2023-08-07 16:05
@Kha 

> So in summary, having separate commands for syncing the lockfile (and dep checkouts) and for upgrading dependencies seems to be a common design, and `lake update deletedPkg` likely is _not_ the way to go :) .

I am not sure how you got this from my explanation, so apparently I was not the clearest.  In Ruby, `bundle update` does do all three (update dependencies, the lockfile, and dependency checkouts) like `lake update` does.  dep checkouts, and updated dependencies) The difference between Ruby and Lake in build/package management are that there are three commands `rake` (for builds), `bundle install` (for dep checkout and "conservative updating") and `bundle update` (for general updating). In Lake, we only have two `lake build` and `lake update`. Currently, `lake build` does building, dependency checkout, and no "conservative updating". We combined building and dependency checkout to follow `cargo`'s example, thus removing the need for `bundle install` / `npm install` of other package managers (which cargo also lacks). Whether this was a good idea, though, I think is worth discussing. Since Lean, like interpreted languages, may wish to make use of dependencies outside of a build, separating the dependency checkout into a separate `install` / `configure` command is worth considering.

> From a quick scan I did not find these reasons btw

Yeah, reading though it again, Gabriel mentioned the philosophy, but we did not discuss the reasons for it there. From what I recall, We wanted to avoid any potential regressions like the linked issues that could cause `lake build` to improperly update the state when a different behavior was desired. This is a discussion that is probably worth revisiting to determine if a "conservative update" should be part of a build like it is in and Bundler and Cargo (at least, that is what [cargo#1670](https://github.com/rust-lang/cargo/issues/1670) suggests).


> If we want more data before we make a decision here, perhaps a survey of (prominent) package managers regarding these properties would be helpful.

Sure,, I am happy to have this discussion.  I would use [GitHub language support](https://docs.github.com/en/get-started/learning-about-github/github-language-support) (+ Rust) as a guide to what the prominent package managers are.

**Comment by tydeu** [comment] 2023-08-07 16:14
@Kha Regardless of future plans and refactors, I think per-package `lake update <pkg> ` is still a worthwhile feature to add and is supported by the prominent package managers:
* [`bundle update <pkg>`](https://bundler.io/v2.4/man/bundle-update.1.html)
* [`npm update <pkg>`](https://docs.npmjs.com/cli/v8/commands/npm-update)
* [`cargo update -p <pkg>`](https://doc.rust-lang.org/cargo/commands/cargo-update.html)
* [`pip install -U <pkg>`](https://pip.pypa.io/en/stable/cli/pip_install/)
* [`composer update <pkg>`](https://getcomposer.org/doc/03-cli.md#update-u-upgrade)

**Comment by Kha** [comment] 2023-08-07 16:17
Absolutely. Recall that I opened this discussion because I disagreed with closing the issue :) .

**Comment by tydeu** [comment] 2023-08-07 16:26
@Kha Good point! XD I think the "`lake update deletedPkg` likely is not the way to go" comment gave me the wrong impression that were questioning the utility of `lake update <pkg>` more generally, rather than just the deleted case. However, I would assume that with this feature that `lake update deletedPkg` would still end up removing the package from the manifest (even if that does not end up being the preferred way to go about due to the use of some other dependency checkout command).

**Comment by Kha** [comment] 2023-08-07 16:38
Mh, I think I would expect that to throw an error saying that the dependency is unknown. I would be quite surprised if that was not the case for the package managers you mentioned.

**Comment by tydeu** [comment] 2023-08-07 19:52
@kha It at least works that way for `composer update` (see this [StackOverflow post](https://stackoverflow.com/questions/27944795/composer-remove-a-package-clean-up-dependencies-dont-update-other-packages)).

**Comment by Kha** [comment] 2023-08-08 07:16
Thanks, that's good to know. The people in the thread don't exactly seem happy about it :smile: .

**Comment by Kha** [comment] 2023-08-08 07:37
> In Ruby, bundle update does do all three (update dependencies, the lockfile, and dependency checkouts)

I think I realized one source of miscommunication - when I say that separating syncing and updating dependencies into different actions seems to be a common, desirable pattern, I don't mean that these commands should be *disjoint*. I fully expect the "update" action to have *strictly more* effects than the "sync" action in any of these package managers (and I only use "action" instead of "command" here because as you mentioned, some of these package mangers sync automatically; in fact, Nix takes this to the extreme by giving users that choice via `--no-write-lockfile`).

**Closed** 2023-08-15 07:50 UTC
Labels: enhancement
