### ISSUE TITLE
Non-pinned dependencies considered harmful

### ISSUE THREAD

**Issue by Kha** [leanprover/lake#59] opened 2022-03-10 13:32 UTC
I start seeing some packages depending on e.g. the `main` branch of a dependency in their lakefile.lean. I consider this an unacceptable anti-pattern for reproducibility, so I'd prefer Lake not to accept it in the first place, e.g. by enforcing 40-character hexstrings for the revision. A lockfile solution would be even nicer, of course, but I wouldn't like to wait for it and watch the anti-pattern proliferate in the meantime.

**Comment by tydeu** [comment] 2022-03-10 21:21
"I'd prefer Lake not to accept it in the first place, e.g. by enforcing 40-character hexstrings for the revision" This won't work because Lake also accepts pinning a dependency at a tag, which is reproducible but does not fit this pattern.

Personally, I think the lockfile solution is simplest way to resolve this, as it doesn't require any end user changes.

**Comment by gebner** [comment] 2022-03-11 08:31
> This won't work because Lake also accepts pinning a dependency at a tag, which is reproducible

Strictly speaking, tags are not reproducible either.

> Personally, I think the lockfile solution is simplest way to resolve this, as it doesn't require any end user changes.

Both options require changes in the end-user workflow, if that workflow depended on lake always grabbing the latest version.  We explicitly want to disallow that workflow because it breaks reproducibility.

With lockfiles, the user would need to run a `lake update` command that updates the versions in the lockfile (c.f. `nix flake update` or `cargo update`).  A lockfile that is updated automatically or not checked in is just as problematic as setting the version to `main`.

**Comment by tydeu** [comment] 2022-03-11 09:26
> Strictly speaking, tags are not reproducible either.

How so? (I was under the impression they were.)
 
> With lockfiles, the user would need to run a `lake update` command that updates the versions in the lockfile (c.f. `nix flake update` or `cargo update`). A lockfile that is updated automatically or not checked in is just as problematic as setting the version to `main`.

True, it would change the development CLI workflow slightly, but it would require no lakefile changes (which was the vector I was thinking of). Implementation-wise  I was thinking of integrating the behavior into `lake configure` to make it actually useful for something. Furthermore,, `lake print-paths` could also update the lockfile/manifest, which would make the change nearly invisible for most use cases.

**Comment by gebner** [comment] 2022-03-11 09:51
> How so? (I was under the impression they were.)

Tags are nonreproducible in the sense that you can change them if you want; see the `-f` option of `git tag`.  It's certainly much less of a problem than referring to branches, which are meant to be updated.  (But people change release tarballs and tags all the time, as anybody with experience in a linux distribution can tell you.)

> Furthermore,, lake print-paths could also update the lockfile/manifest, which would make the change nearly invisible for most use cases.

This negates all advantages of a lockfile.  A lockfile that is automatically updated is functionally the same as no lockfile at all.

**Comment by tydeu** [comment] 2022-03-11 10:03
@gebner 

> Tags are nonreproducible in the sense that you can change them if you want; see the `-f` option of `git tag`.

True, but then, strictly speaking, commits are not reproducible either, right? That is, you can do a `git rebase` and wipe all trace of the existence of a given commit. There is the caveat that, unlike tags, you can't feasibly *change* the content of a commit (as it is a content hash), but that's more of a security concern of tags than a reproducibility one. It is also an issue that can be addressed by having the manifest/lockfile contain a content hash for the dependency to check against.

> This negates all advantages of a lockfile. A lockfile that is automatically updated is functionally the same as no lockfile at all.

As I understand it, the general use case of a lockfile is for CI/CD or one time builds, not development. In those cases one would use `lake build`, which would not update the lockfile (thus providing the desired benefit). During development though, you generally do want the latest acceptable dependency for all those listed (both old and new), so you do want it automatically updated. Right?

**Comment by gebner** [comment] 2022-03-11 10:49
> True, but then, strictly speaking, commits are not reproducible either, right?  That is, you can [...] wipe all trace of the existence of a given commit.

In this sense, nothing is reproducible because the server might be down, you might not have an internet connection, the government censors your code, etc.

Reproducible typically means that you get the same result if it succeeds.  What we want to avoid is a situation where you silently get a different version of a dependency and then it works for you but not the other guy on the team.

> As I understand it, the general use case of a lockfile is for CI/CD or one time builds, not development.

I vehemently disagree with this assessment.  The purpose of a lockfile is to ensure that everybody has the same dependency version by making version updates an explicit, reviewable step.

As an example, say that `mathlib` depends on `aesop`.  What we really, really want to avoid is errors of the form "aesop pushed a breaking change to master today, so you can't work on mathlib anymore".  (Which would happen if print-paths updated the lockfile.)  Automatically updating dependencies in any form is simply unacceptable.

**Comment by tydeu** [comment] 2022-03-11 13:19
@gebner

> What we want to avoid is a situation where you silently get a different version of a dependency and then it works for you but not the other guy on the team. ... The purpose of a lockfile is to ensure that everybody has the same dependency version by making version updates an explicit, reviewable step.

Interesting, I have heard this be mentioned as a reason for reproducibility, but I have never heard it touted as its main purpose. Especially since I have heard of and seen workflows were artifacts like lockfiles are not committed (which explicitly excludes this use case).

Regardless, there are many ways to address these qualms with the current proposal. For one, not have `lake print-paths` auto-update the lockfile (or make it an option).  Furthermore, Even if `lake print-paths` *does* auto-update the lockfile and it is committed, that would still be a part of the changelist (and could be reverted by the user if they don't wish to change it in a PR). In general, a manifest / lockfile still seems like the most direct way to resolve the initial issue / feature request with minimal distrubance to the end users.

**Closed** 2022-05-24 00:39 UTC
Labels: enhancement
